import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const NunitoSans = Nunito({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Calculadora de IMC (BMI)s",
  //description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${NunitoSans.variable}  antialiased`}>{children}</body>
    </html>
  );
}
